services:
  # UI dashboard
  dvwa-db:
    image: whackers/dvwa_db:latest
    container_name: dvwa-db
    restart: unless-stopped
    networks: [dvwa-net]
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"

  dvwa-web:
    image: whackers/dvwa_web:latest
    container_name: dvwa-web
    restart: unless-stopped
    networks: [dvwa-net]
    ports:
      - '127.0.0.1:8081:80'
    depends_on:
      - dvwa-db
    volumes:
      - ./dvwa_web/config.inc.php:/var/www/html/config/config.inc.php:ro
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"

  # Main proxy service
  proxy:
    image: whackers/zentinel:26.03_2
    container_name: zentinel-proxy
    user: "65532:65532"
    ports:
      - "8084:8080"   # HTTP
      - "443:8443"   # HTTPS
      - "9090:9090"   # Health/Metrics
    volumes:
      - ./config/proxy/proxy.kdl:/etc/zentinel/config.kdl:ro
      - ./config/proxy/certs:/etc/zentinel/tls
      - proxy-data:/var/lib/zentinel
      - proxy-logs:/var/log/zentinel
      - share-sockets:/var/run/zentinel
    environment:
      RUST_LOG: info,zentinel_proxy=debug
      ZENTINEL_CONFIG: /etc/zentinel/config.kdl
    networks: [dvwa-net]
    depends_on:
      - dvwa-web
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: unless-stopped
  
  waf:
    container_name: waf
    image: whackers/zentinel-agent-waf:v0.3.0
    user: "65532:65532"
    ports:
      - "9094:9094"
    volumes:
      - share-sockets:/var/run/zentinel
    environment:
      AGENT_GRPC_ADDRESS: 0.0.0.0:9094
      RUST_LOG: "debug"
    networks: [dvwa-net]
    restart: unless-stopped
  
  zentinelsec:
    container_name: zentinelsec
    image: whackers/zentinelsec-agent:debug
    user: "0:0"
    ports:
      - "9095:9095"
    volumes:
      - share-sockets:/var/run/zentinel
      - ./config/modsec/:/etc/modsecurity
    environment:
      AGENT_GRPC_ADDRESS: 0.0.0.0:9095
      ZENTINELSEC_EXCLUDE_PATHS: "/health,/metrics"
      ZENTINELSEC_BLOCK_MODE: "true"
      AGENT_SOCKET: "/var/run/zentinel/zentinelsec.sock"
      ZENTINELSEC_RULES: "/etc/modsecurity/config/include.conf"
      RUST_LOG: "debug"
    networks: [dvwa-net]
    restart: unless-stopped  


volumes:
  proxy-data:
    driver: local
  proxy-logs:
    driver: local
  share-sockets:

networks:
  dvwa-net:
    driver: bridge
